### ISSUE TITLE
set-output and nodejs12 issue

### ISSUE THREAD

**Issue by Geordam** [moia-oss/setup-eksctl#13]
Set-output is deprecated and will no longer be usable from 1st of june. 
Nodejs12 is also deprecated and we get a warning when using this action.
When using your action

> Run moia-oss/setup-eksctl@v2

I get :

> Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
and

> Warning:  Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: moia-oss/setup-eksctl@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

**Comment by cbrgm** [comment]
Heyho! This should be resolved now with [v2.2.0](https://github.com/moia-oss/setup-eksctl/releases/tag/v2.2.0) .
